### ISSUE TITLE
Get a first stab at farm budgets.

### ISSUE THREAD

**Issue by qjhart** [CSTARS/farm-budgets-app#1]
The farm budget app needs to have some data generated from some existing spreadsheets.  [Santiago's spreadsheet](https://docs.google.com/spreadsheets/d/1FEcafJQj2sCzQ6vGxlLp-DAEB4p28mC_g37IVD5L4UU/edit#gid=385810702) includes a number of these data.  We need to simplify and standardize this spreadsheet.  This can be done either by replicating and modifying, or someother manner, but we need sheets (or CSVs ) that are of the form: 

| State | commodity | item | amount | unit |
| --- | --- | --- | --- | --- |
| CA | alfalfa | 11-52-0 | 75 | lb |
| CA | alfalfa | Lorsban 4E | 2 | pint |
| CA | alfalfa | ... | ... | ... |

You can see this could all go on a single sheet in the database.

We will also need to collect costs as well.  That could be done either with the same table (with a new row), or since that's not normalized, with a second table, however, it's fine to normalize on in the dB after, so whichever is easiest.

| State | item | cost | unit |
| --- | --- | --- | --- |
| CA | 11-52-0 | $0.44 | lb |
| CA | Lorsban 4E | $8.65 | pint |
| CA | ... | ... | ... |

I

**Comment by jrmerz** [comment]
Do we need to protect the demo if I start adding sample data from this
spreadsheet?

**Comment by qjhart** [comment]
Yes, that's not and issue.

**Comment by jrmerz** [comment]
I split this out a little bit more, hoping to provide human-readable/editable csv files.  Example file structure / csv structure: https://github.com/CSTARS/farm-budgets-data/blob/master/data/California/costs/default.csv and https://github.com/CSTARS/farm-budgets-data/blob/master/data/California/amounts/Alfalfa/default.csv.

Basically:
- State / [optional county/zip locality] / costs / budgetname.csv 
- State / [optional county/zip locality] / amounts / crop / budgetname.csv
