### ISSUE TITLE
Updates to Complex Materials do not generate new Operation Calculations

### ISSUE THREAD

**Issue by qjhart** [CSTARS/farm-budgets-app#14]
If you edit a complex material, operations that use that material do not automatically update their subtotal.  The easiest thing to do is edit the amount to get a recalc, but that is not budget wide.

**Comment by jrmerz** [comment]
@qjhart can you pull and retest?  I thought I pushed that fix.

**Comment by jrmerz** [comment]
@qjhart I think this was fixed.  Feel free to re-open if that is not the case.
