### ISSUE TITLE
TIme units in 'Schedule'

### ISSUE THREAD

**Issue by peteWT** [CSTARS/farm-budgets-app#21]
When scheduling an operation I was not able to select a unit other than 'Months'. Select window shows up but regardless of what I clicked on (Say, Month, Year), result is always 'Month'.

**Comment by jrmerz** [comment]
@peteWT Humm, seems to be working on my end.  Can you provide OS & browser?

**Comment by peteWT** [comment]
@jrmerz Firefox 42.0 Linux Mint LMDE 2 Cinnamon 64-bit kernel 3.16.0-4-amd64

**Comment by jrmerz** [comment]
@peteWT Think I got it, sorry for the delay.  Please reopen if still not working.
