### ISSUE TITLE
Changes to operations not showing save button

### ISSUE THREAD

**Issue by jrmerz** [CSTARS/farm-budgets-app#22]
When you create a new operation or modify an existing operation, the save changes button should show.  Currently it isn't.

**Comment by jrmerz** [comment]
@hitchpy @peteWT FYI

**Comment by jrmerz** [comment]
@hitchpy @peteWT Sorry about this bug, go ahead and try again.  Changes to operations should now show the save btn.

**Comment by jrmerz** [comment]
Let me know if you still have issues, otherwise closing.

**Comment by peteWT** [comment]
Works for me. Thanks!  

## 

Peter Tittmann
(707) 849-4135
