### ISSUE TITLE
Suggest our service endpoint scenario

### ISSUE THREAD

**Issue by qjhart** [CSTARS/farm-budgets-app#3]
There have been a few examples of service endpoints to use.  Including; Google Visualization sources, Google Fusion Table ; Swagger declarative; mongo; and Firebase (both potentially view pgRest).  We need to decide which type of endpoint we are going with for this budget app.

**Comment by jrmerz** [comment]
Think we have decided, correct?  ExpressJS / Postgres, currently hosted at farm-budgets.bioenergy.casil.ucdavis.edu.  @qjhart closing, feel free to reopen if you disagree.

**Comment by qjhart** [comment]
I think we should look at pgRest as a possibility for it's auto JSON generation (if such a thing is any good).

**Comment by jrmerz** [comment]
For pgREST, I don't like the combo of the WIP status, the current version number and the fact it hasn't been touched in 4 months.  just concerns.
