### ISSUE TITLE
Administrative Interface

### ISSUE THREAD

**Issue by qjhart** [CSTARS/farm-budgets-app#6]
II have a simple UI (with Oauth authentication) for admins to add budgets.  The admins can add costs for items at different localities.  Currently the admin frontend only supports at state level state.  But the backend (Rest API) and main application support county and zipcode level localities as well.  The admins can then add items/amount required for a selected crop at the locality.

The current drawbacks to administrative interface are the inputs are single line text input.  So someone has to use this admin interface to add/edit data.  Which seems nice for edits, but bad for large additions.  Obviously the thought of ingest from a spreadsheet is floating around in my mind.

**Comment by qjhart** [comment]
We should probably understand the level of effort here vs. tradeoff here.  More than likely, we will be the administrative role for the data for the next 2yrs.  So any strategy that relies on direct modification of the database is probably not a bad idea, at leas t in the short term.

**Comment by jrmerz** [comment]
I'm going to close this under the pretense that we have made a decision on the admin interface.  It will be a local node-webkit app, modifying csv files that will be pushed into Postgres.  Issues from here on out should probably be made under the the data repo or the editor repo (if we decide a new repo is required)
